
name: Daily Reward Auto-Claim

on:
  schedule:
    - cron:  0 8 * * * 
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version:  3.9 

      - name: Install dependencies
        run: pip install requests

      - name: Run Claim Script
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          python -c "import requests, os; token = os.environ.get( AUTH_TOKEN ); url =  https://giftcode.betelgeuse.app/api/daily-rewards/claim ; headers = { Authorization : token,  User-Agent :  okhttp/5.3.2 }; response = requests.post(url, headers=headers); print(f Status Code: {response.status_code} ); print(f Response: {response.text} )"
